DESCRIPTION: Hello World
SQL: SELECT substr(li, 1, 2) AS lang, count(li) AS cnt FROM papaqmilog WHERE li != "NA" AND to_date(t) BETWEEN ":DATE_START" AND ":DATE_END" GROUP BY substr(li, 1, 2) ORDER BY cnt DESC
CHART: pie
INPUT:
  - DATE_START
  - DATE_END
OUTPUT:
  NAME: lang
  VALUE: cnt