TITLE: 每月使用量
DESCRIPTION: Hello World
SQL: SELECT to_date(t) as d, count(DISTINCT ui) AS cnt FROM papaqmilog WHERE to_date(t) BETWEEN ":DATE_START" AND ":DATE_END" GROUP BY d ORDER BY d ASC, cnt DESC;
INPUT:
  - DATE_START: $1
  - DATE_END: $2
OUTPUT:
  - X: d
  - Y: cnt
