#!/usr/bin/env node

var concat = require('concat-stream');

process.stdin.pipe(concat(function (body) {
  var json = JSON.parse(body);

  var options = {
    chart: {
      type: "column"
    },
    title: {
      text: "2018-1"
    },
    xAxis: {
      categories: []
    },
    yAxis: {
      title: {
        text: "Persons"
      }
    },
    series: [{
      data: []
    }]
  };

  for (var e in json) {
    options.xAxis.categories.push(json[e]["to_date(t)"]);
    options.series[0].data.push(+json[e]["cnt"]);
  }

  console.log(JSON.stringify(options));
}));
