#!/usr/bin/env node

var concat = require('concat-stream');

process.stdin.pipe(concat(function (body) {
  var json = JSON.parse(body);
  var args = process.argv.slice(2);

  var options = {
    chart: {
      type: "column"
    },
    title: {
      text: args[0]
    },
    xAxis: {
      categories: []
    },
    yAxis: {
      title: {
        text: "Persons"
      }
    },
    series: [{
      data: []
    }]
  };

  for (var e in json) {
    options.xAxis.categories.push(json[e][args[1]]);
    options.series[0].data.push(+json[e][args[2]]);
  }

  console.log(JSON.stringify(options));
}));
